<option value="AFG">AFGHANISTAN</option>
<option value="ALB">ALBANIA</option>
<option value="DZA">ALGERIA</option>
<option value="AND">ANDORRA</option>
<option value="AGO">ANGOLA</option>
<option value="ATG">ANTIGUA AND BARBUDA</option>
<option value="ARG">ARGENTINA</option>
<option value="ARM">ARMENIA</option>
<option value="AUS">AUSTRALIA</option>
<option value="AUT">AUSTRIA</option>
<option value="AZE">AZERBAIJAN</option>
<option value="BHS">BAHAMAS</option>
<option value="BHR">BAHRAIN</option>
<option value="BGD">BANGLADESH</option>
<option value="BRB">BARBADOS</option>
<option value="BLR">BELARUS</option>
<option value="BEL">BELGIUM</option>
<option value="BLZ">BELIZE</option>
<option value="BEN">BENIN</option>
<option value="BMU">BERMUDA</option>
<option value="BTN">BHUTAN</option>
<option value="BOL">BOLIVIA</option>
<option value="BIH">BOSNIA AND HERZEGOVINA</option>
<option value="BWA">BOTSWANA</option>
<option value="BRA">BRAZIL</option>
<option value="IOT">BRITISH INDIAN OCEAN TERRITORY</option>
<option value="BRN">BRUNEI DARUSSALAM</option>
<option value="BGR">BULGARIA</option>
<option value="BFA">BURKINA FASO</option>
<option value="BDI">BURUNDI</option>
<option value="KHM">CAMBODIA</option>
<option value="CMR">CAMEROON</option>
<option value="CAN">CANADA</option>
<option value="CPV">CAPE VERDE</option>
<option value="CYM">CAYMAN ISLANDS</option>
<option value="CAF">CENTRAL AFRICAN REPUBLIC</option>
<option value="TCD">CHAD</option>
<option value="CHL">CHILE</option>
<option value="CHN">CHINA</option>
<option value="COL">COLOMBIA</option>
<option value="COM">COMOROS</option>
<option value="COG">CONGO</option>
<option value="COK">COOK ISLANDS</option>
<option value="CRI">COSTA RICA</option>
<option value="CIV">COTE D'IVOIRE</option>
<option value="HRV">CROATIA</option>
<option value="CUB">CUBA</option>
<option value="CYP">CYPRUS</option>
<option value="CZE">CZECH REPUBLIC</option>
<option value="DNK">DENMARK</option>
<option value="DJI">DJIBOUTI</option>
<option value="DOM">DOMINICAN REPUBLIC</option>
<option value="TMP">EAST TIMOR</option>
<option value="ECU">ECUADOR</option>
<option value="EGY">EGYPT</option>
<option value="SLV">EL SALVADOR</option>
<option value="GNQ">EQUATORIAL GUINEA</option>
<option value="ERI">ERITREA</option>
<option value="EST">ESTONIA</option>
<option value="ETH">ETHIOPIA</option>
<option value="FLK">FALKLAND ISLANDS (MALVINAS)</option>
<option value="FRO">FAROE ISLANDS</option>
<option value="FJI">FIJI</option>
<option value="FIN">FINLAND</option>
<option value="FRA">FRANCE</option>
<option value="PYF">FRENCH POLYNESIA</option>
<option value="GAB">GABON</option>
<option value="GMB">GAMBIA</option>
<option value="GEO">GEORGIA</option>
<option value="DEU">GERMANY</option>
<option value="GHA">GHANA</option>
<option value="GIB">GIBRALTAR</option>
<option value="GRC">GREECE</option>
<option value="GRL">GREENLAND</option>
<option value="GRD">GRENADA</option>
<option value="GLP">GUADELOUPE</option>
<option value="GUM">GUAM</option>
<option value="GTM">GUATEMALA</option>
<option value="GIN">GUINEA</option>
<option value="GNB">GUINEA-BISSAU</option>
<option value="HTI">HAITI</option>
<option value="VAT">HOLY SEE (VATICAN CITY STATE)</option>
<option value="HND">HONDURAS</option>
<option value="HKG">HONG KONG</option>
<option value="HUN">HUNGARY</option>
<option value="ISL">ICELAND</option>
<option value="IND">INDIA</option>
<option value="IDN">INDONESIA</option>
<option value="IRQ">IRAQ</option>
<option value="IRL">IRELAND</option>
<option value="IRN">ISLAMIC REPUBLIC OF IRAN</option>
<option value="ISR">ISRAEL</option>
<option value="ITA">ITALY</option>
<option value="JAM">JAMAICA</option>
<option value="JPN">JAPAN</option>
<option value="JOR">JORDAN</option>
<option value="KAZ">KAZAKHSTAN</option>
<option value="KEN">KENYA</option>
<option value="KIR">KIRIBATI</option>
<option value="KWT">KUWAIT</option>
<option value="KGZ">KYRGYZSTAN</option>
<option value="LAO">LAO PEOPLE'S DEMOCRATIC REPUBLIC</option>
<option value="LVA">LATVIA</option>
<option value="LBN">LEBANON</option>
<option value="LSO">LESOTHO</option>
<option value="LBR">LIBERIA</option>
<option value="LBY">LIBYAN ARAB JAMAHIRIYA</option>
<option value="LIE">LIECHTENSTEIN</option>
<option value="LTU">LITHUANIA</option>
<option value="LUX">LUXEMBOURG</option>
<option value="MAC">MACAO</option>
<option value="MDG">MADAGASCAR</option>
<option value="MWI">MALAWI</option>
<option value="MYS">MALAYSIA</option>
<option value="MDV">MALDIVES</option>
<option value="MLI">MALI</option>
<option value="MLT">MALTA</option>
<option value="MTQ">MARTINIQUE</option>
<option value="MRT">MAURITANIA</option>
<option value="MUS">MAURITIUS</option>
<option value="MEX">MEXICO</option>
<option value="MCO">MONACO</option>
<option value="MNG">MONGOLIA</option>
<option value="MAR">MOROCCO</option>
<option value="MOZ">MOZAMBIQUE</option>
<option value="MMR">MYANMAR</option>
<option value="NAM">NAMIBIA</option>
<option value="NRU">NAURU</option>
<option value="NPL">NEPAL</option>
<option value="NLD">NETHERLANDS</option>
<option value="ANT">NETHERLANDS ANTILLES</option>
<option value="NCL">NEW CALEDONIA</option>
<option value="NZL">NEW ZEALAND</option>
<option value="NIC">NICARAGUA</option>
<option value="NER">NIGER</option>
<option value="NGA">NIGERIA</option>
<option value="MNP">NORTHERN MARIANA ISLANDS</option>
<option value="NOR">NORWAY</option>
<option value="OMN">OMAN</option>
<option value="PAK">PAKISTAN</option>
<option value="PLW">PALAU</option>
<option value="PSE">PALESTINIAN TERRITORY, OCCUPIED</option>
<option value="PAN">PANAMA</option>
<option value="PNG">PAPUA NEW GUINEA</option>
<option value="PRY">PARAGUAY</option>
<option value="PER">PERU</option>
<option value="PHL">PHILIPPINES</option>
<option value="POL">POLAND</option>
<option value="PRT">PORTUGAL</option>
<option value="PRI">PUERTO RICO</option>
<option value="QAT">QATAR</option>
<option value="KOR">REPUBLIC OF KOREA</option>
<option value="MDA">REPUBLIC OF MOLDOVA</option>
<option value="REU">REUNION</option>
<option value="ROM">ROMANIA</option>
<option value="RUS">RUSSIAN FEDERATION</option>
<option value="RWA">RWANDA</option>
<option value="WSM">SAMOA</option>
<option value="SMR">SAN MARINO</option>
<option value="STP">SAO TOME AND PRINCIPE</option>
<option value="SAU">SAUDI ARABIA</option>
<option value="SEN">SENEGAL</option>
<option value="YUG">SERBIA AND MONTENEGRO</option>
<option value="SYC">SEYCHELLES</option>
<option value="SLE">SIERRA LEONE</option>
<option value="SGP">SINGAPORE</option>
<option value="SVK">SLOVAKIA</option>
<option value="SVN">SLOVENIA</option>
<option value="SLB">SOLOMON ISLANDS</option>
<option value="SOM">SOMALIA</option>
<option value="ZAF">SOUTH AFRICA</option>
<option value="ESP">SPAIN</option>
<option value="LKA">SRI LANKA</option>
<option value="SDN">SUDAN</option>
<option value="SUR">SURINAME</option>
<option value="SWZ">SWAZILAND</option>
<option value="SWE">SWEDEN</option>
<option value="CHE">SWITZERLAND</option>
<option value="SYR">SYRIAN ARAB REPUBLIC</option>
<option value="TWN">TAIWAN</option>
<option value="TJK">TAJIKISTAN</option>
<option value="THA">THAILAND</option>
<option value="COD">THE DEMOCRATIC REPUBLIC OF THE CONGO</option>
<option value="MKD">THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA</option>
<option value="TGO">TOGO</option>
<option value="TON">TONGA</option>
<option value="TTO">TRINIDAD AND TOBAGO</option>
<option value="TUN">TUNISIA</option>
<option value="TUR">TURKEY</option>
<option value="TKM">TURKMENISTAN</option>
<option value="TUV">TUVALU</option>
<option value="UGA">UGANDA</option>
<option value="UKR">UKRAINE</option>
<option value="ARE">UNITED ARAB EMIRATES</option>
<option value="GBR">UNITED KINGDOM</option>
<option value="TZA">UNITED REPUBLIC OF TANZANIA</option>
<option value="USA">UNITED STATES</option>
<option value="URY">URUGUAY</option>
<option value="UZB">UZBEKISTAN</option>
<option value="VUT">VANUATU</option>
<option value="VEN">VENEZUELA</option>
<option value="VNM">VIET NAM</option>
<option value="VGB">VIRGIN ISLANDS, BRITISH</option>
<option value="YEM">YEMEN</option>
<option value="ZMB">ZAMBIA</option>
<option value="ZWE">ZIMBABWE</option>