EasySocial.require()
	.script(
		"site/likes/likes",
		"site/reports/reports",
		"site/repost/repost",
		"site/share/share",
		"site/layout/dialog",
		"site/layout/responsive",
		"site/layout/elements",
		"site/photos/photos",
		"site/users/login",
		"site/profile/popbox",
		"site/privacy/privacy",
		"site/locations/popbox",
		"site/sidebar/sidebar",
		"site/friends/api",
		"site/conversations/api",
		"site/followers/api",
		"site/popbox/popbox"
	)
	.done();
